In [1]:
import numpy as np

In [2]:
np.linalg.norm([3,4])

5.0

In [3]:
np.linalg.norm([-4, -3, -2, -1,  0,  1,  2,  3,  4])

7.745966692414834

In [4]:
(16 + 9 + 4 + 1)*2

60

In [6]:
np.dot([[2,4,6],[1,2,3
                         ]], [1,2,3])

array([28, 14])

In [10]:
np.linalg.norm([[2,4,6],[1,2,3],[2,4,6],[2,4,6]], axis = 1)

array([ 7.48331477,  3.74165739,  7.48331477,  7.48331477])

In [11]:
np.array([[2,4,6],[1,2,3],[2,4,6],[2,4,6]])

array([[2, 4, 6],
       [1, 2, 3],
       [2, 4, 6],
       [2, 4, 6]])

In [12]:
np.array([[2,4,6],[1,2,3],[2,4,6],[2,4,6]]).shape

(4, 3)

In [13]:
dum = np.array([[2,4,6],[1,2,3],[2,4,6],[2,4,6]])

In [16]:
np.linalg.norm(dum, axis=1).shape

(4,)

In [ ]:
np.multiply(np.linalg.norm(Wv, axis=1),np.linalg.norm(v))

In [17]:
np.multiply(dum, [2])

array([[ 4,  8, 12],
       [ 2,  4,  6],
       [ 4,  8, 12],
       [ 4,  8, 12]])

In [18]:
dum

array([[2, 4, 6],
       [1, 2, 3],
       [2, 4, 6],
       [2, 4, 6]])

In [19]:
np.sum(dum, axis=1)

array([12,  6, 12, 12])

In [20]:
np.sum(dum, axis=0)

array([ 7, 14, 21])

In [21]:
np.divide(dum, [2])

array([[ 1. ,  2. ,  3. ],
       [ 0.5,  1. ,  1.5],
       [ 1. ,  2. ,  3. ],
       [ 1. ,  2. ,  3. ]])

In [22]:
np.divide(dum, 2)

array([[ 1. ,  2. ,  3. ],
       [ 0.5,  1. ,  1.5],
       [ 1. ,  2. ,  3. ],
       [ 1. ,  2. ,  3. ]])

In [26]:
np.diff(np.array([0,5]),np.array([2,3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
np.array([0.5])

array([ 0.5])

In [27]:
np.array([0,5])

array([0, 5])

In [28]:
np.array([2,3])

array([2, 3])

In [35]:
np.array([0,1,5]) - np.array([2,1,13])

array([-2,  0, -8])

In [33]:
np.diff(np.array([0,5,1]), np.array([2,3,1]), axis = 1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()